export const alertConstants = {
    SUCCESS: 'ALERT_SUCCESS',
    ERROR: 'ALERT_ERROR',
    CLEAR: 'ALERT_CLEAR'
};

export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    
    LOGOUT: 'USERS_LOGOUT',

    GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    GETALL_FAILURE: 'USERS_GETALL_FAILURE',

    DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    DELETE_FAILURE: 'USERS_DELETE_FAILURE'    
};

export const gameHistoryConstants = {
    GETALL_REQUEST: 'GAME_HISTORY_GETALL_REQUEST',
    GETALL_SUCCESS: 'GAME_HISTORY_GETALL_SUCCESS',
    GETALL_FAILURE: 'GAME_HISTORY_GETALL_FAILURE',

    GETALL_REQUEST: 'GAME_HISTORY_GETONE_REQUEST',
    GETALL_SUCCESS: 'GAME_HISTORY_GETONE_SUCCESS',
    GETALL_FAILURE: 'GAME_HISTORY_GETONE_FAILURE',

    DELETE_REQUEST: 'GAME_HISTORY_DELETE_REQUEST',
    DELETE_SUCCESS: 'GAME_HISTORY_DELETE_SUCCESS',
    DELETE_FAILURE: 'GAME_HISTORY_DELETE_FAILURE'
};